// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3JhPPq3fZHiZm-mLeKGnGON3i75whAKI',
    appId: '1:956056830725:web:71f240ce5f917265746d6c',
    messagingSenderId: '956056830725',
    projectId: 'flutteruserproject-e0ee0',
    authDomain: 'flutteruserproject-e0ee0.firebaseapp.com',
    storageBucket: 'flutteruserproject-e0ee0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6A6rvtrK2uBgFXXMU_HDH97OWEbg1mg0',
    appId: '1:956056830725:android:4ef9352ae001e6ae746d6c',
    messagingSenderId: '956056830725',
    projectId: 'flutteruserproject-e0ee0',
    storageBucket: 'flutteruserproject-e0ee0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-yh561v6SS6Wg8OZ3XSZK9wcyXVNWBU',
    appId: '1:956056830725:ios:dfcb400a7db09eee746d6c',
    messagingSenderId: '956056830725',
    projectId: 'flutteruserproject-e0ee0',
    storageBucket: 'flutteruserproject-e0ee0.firebasestorage.app',
    iosBundleId: 'com.example.flutterUserProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3JhPPq3fZHiZm-mLeKGnGON3i75whAKI',
    appId: '1:956056830725:web:830b42bbe9896596746d6c',
    messagingSenderId: '956056830725',
    projectId: 'flutteruserproject-e0ee0',
    authDomain: 'flutteruserproject-e0ee0.firebaseapp.com',
    storageBucket: 'flutteruserproject-e0ee0.firebasestorage.app',
  );
}
